### PR TITLE
adds toggle to switches.

### PR DESCRIPTION
**Pull request by ianhundere**
this PR adds a toggle option to switches.

@markwheeler if this checks out, i can circle back around and make the necessary `web-config` changes.

thanks for all of your hard work building this. 🚀 / 🙇🏼

### CODE REVIEW

**Comment by ianhundere** [comment]
@markwheeler if this checks out, i can circle back around and make the necessary `web-config` changes.

thanks for all of your hard work building this. 🚀 / 🙇🏼

**Comment by markwheeler** [comment]
Hi, a toggle mode makes sense to me as an addition, thanks for starting on it! As you mention I think it would need to be user-configurable to make sense in an 'official' release.

**Comment by ianhundere** [comment]
@markwheeler okidoki, i "think" those are the necessary changes for the `web-config`.

**Comment by ianhundere** [comment]
i tried compiling via the arduino ide and got the following error(s):
```
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void setup()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:112:3: error: 'usbMIDI' was not declared in this scope
  112 |   usbMIDI.setHandleSystemExclusive(processSysexChunk);
      |   ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void sendAllPotValues()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:117:5: error: 'usbMIDI' was not declared in this scope
  117 |     usbMIDI.sendControlChange(potCCs[i], potMidiValues[i], potChannels[i] + 1);
      |     ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void readPots()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:169:7: error: 'usbMIDI' was not declared in this scope
  169 |       usbMIDI.sendControlChange(potCCs[i], newMidiValue, potChannels[i] + 1);
      |       ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void switchDown(byte)':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:191:5: error: 'usbMIDI' was not declared in this scope
  191 |     usbMIDI.sendControlChange(getSwitchValue(index), value, switchChannel + 1);
      |     ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:195:5: error: 'usbMIDI' was not declared in this scope
  195 |     usbMIDI.sendControlChange(getSwitchValue(index), 127, switchChannel + 1);
      |     ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void switchUp(byte)':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:203:5: error: 'usbMIDI' was not declared in this scope
  203 |     usbMIDI.sendControlChange(getSwitchValue(index), 0, switchChannel + 1);
      |     ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void sendSysexProtocolVersion()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:475:3: error: 'usbMIDI' was not declared in this scope
  475 |   usbMIDI.sendSysEx(RESPONSE_HEADER_LENGTH, SYSEX_RESPONSE_HEADER, false);
      |   ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void sendSysexConfig()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:486:3: error: 'usbMIDI' was not declared in this scope
  486 |   usbMIDI.sendSysEx(RESPONSE_HEADER_LENGTH + PACKED_BYTE_DATA_LENGTH, sysexData, false);
      |   ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void sendWriteFailed()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:490:3: error: 'usbMIDI' was not declared in this scope
  490 |   usbMIDI.sendSysEx(WRITE_FAILED_LENGTH, SYSEX_WRITE_FAILED, false);
      |   ^~~~~~~
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino: In function 'void loop()':
/home/ianfundere/Desktop/midi-mixer-one/firmware/midi_mixer_one/midi_mixer_one.ino:512:10: error: 'usbMIDI' was not declared in this scope
  512 |   while (usbMIDI.read()) {
      |          ^~~~~~~

exit status 1

Compilation error: 'usbMIDI' was not declared in this scope
```

**Comment by ianhundere** [comment]
i tried compiling via the arduino ide and got the following error(s):
```
...
exit status 1

Compilation error: 'usbMIDI' was not declared in this scope
```

edit: never mind, didn't have the proper usb type selected 😅

**Comment by ianhundere** [comment]
@markwheeler okay, looks like the change works, but everything is set to 
toggle so lemme fix that. i'm also getting the grayed out shift dropdowns:
Screenshot from 2024-01-08 16-29-41

**Comment by ianhundere** [comment]
@markwheeler okay, i think i'm almost to the finish line. i've confirmed that the firmware seems to work with the commented out test in `setup()`, but i'm running into an issue when trying to use the web-config ui. i keep getting `Invalid data received.`

any idea what i might be doing wrong?

**Comment by markwheeler** [comment]
There must be an issue in the `unserialize()` function – I'd suggest doing some debugging there.

**Comment by ianhundere** [comment]
word, cheers/thanks.

**Comment by ianhundere** [comment]
ended up using the midi-mixer-one in tandem w/ the [studiologic sl mixface](https://www.studiologic-music.com/products/mixface/) that has (led) midi toggles built-in.

**Pull request closed without merging**
